# Generated by Django 4.0.5 on 2022-06-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_description', models.CharField(max_length=250)),
                ('pet_age', models.CharField(max_length=50)),
                ('pet_kind', models.CharField(max_length=50)),
                ('pet_breed', models.CharField(max_length=50)),
            ],
        ),
    ]
