# Generated by Django 4.0.5 on 2022-06-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='pet_breed',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='pet_kind',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='pet_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_description',
        ),
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
