# Generated by Django 4.0.5 on 2022-06-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0002_rename_pet_age_pet_age_rename_pet_breed_pet_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='img.png', upload_to='pics'),
        ),
    ]
