# Generated by Django 4.0.5 on 2022-06-08 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default=datetime.date.today, max_length=50),
            preserve_default=False,
        ),
    ]
