# Generated by Django 4.0.5 on 2022-06-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0004_pet_date_pet_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(null=True, upload_to='media/pics'),
        ),
    ]
