# Generated by Django 4.0.5 on 2022-06-10 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopt', '0006_alter_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='published_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='pics'),
        ),
    ]
