# Generated by Django 4.0.5 on 2022-06-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0010_kind_alter_pet_description_alter_pet_published_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='kindfk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adopt.kind'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='kind',
            field=models.CharField(max_length=50),
        ),
    ]
