# Generated by Django 4.0.5 on 2022-06-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0013_rename_kindfk_pet_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
