# Generated by Django 4.0.5 on 2022-06-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0014_pet_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='adopt.kind'),
        ),
    ]
