# Generated by Django 4.0.5 on 2022-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0016_alter_pet_age_alter_pet_name_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
