# Generated by Django 4.0.5 on 2022-06-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0018_pet_adopted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='pending',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
