# Generated by Django 4.0.5 on 2022-06-24 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopt', '0020_pet_adopted_by_alter_adoptionrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='adopted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
