# Generated by Django 4.0.5 on 2022-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0021_alter_pet_adopted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Adopted by Another User', 'Adopted by Another User')], default='Pending', max_length=25),
        ),
    ]
